# Generated by Django 4.2.9 on 2024-01-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_task_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tambola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_range', models.IntegerField()),
                ('max_range', models.IntegerField()),
                ('generated_numbers', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
